version: '3.8'

networks:
  challengeProject:
    driver: bridge

services:
  mysqld:
    image: mysql:8.0.27
    restart: on-failure
    networks:
      - filterProject
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=challengeProject